os: osx
dist: trusty
language: node_js
node_js: v10
install:
    - npm i
script:
    - npm test
    - npm run build
deploy:
    provider: npm
    email: smilingxinyi@gmail.com
    skip_cleanup: true
    api_key:
        secure: "57b07839-0e8e-4ee0-a59c-57ed7ef6aeae"
    on:
        tags: true
        repo: "misaka-ink/fetch2"
        branch: master
