os: osx
dist: trusty
language: node_js
node_js: v10
install:
    - npm i
script:
    - npm test
    - npm run build
deploy:
    provider: npm
    email: smilingxinyi@gmail.com
    skip_cleanup: true
    api_key: beed6a27-56ea-4427-939b-1e0312c48613
    on:
        tags: true
        repo: "misaka-ink/fetch2"
        branch: master
